- name: Create infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_scenario_directory: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
  tasks:
    - name: Create KinD cluster
      command: kind create cluster --name {{ item.name }} --config {{ molecule_scenario_directory }}/kind.yaml
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"