- name: Verify OVN
  hosts: all
  tasks:
    - name: Get all pods that are not running after 30 retries
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: openstack
        field_selectors:
          - stats.phase!=Running
      register: _k8s_info
      until: _k8s_info.resources | length == 0
      retries: 30
      delay: 10

    - name: Assert that there are no pods that are not running
      ansible.builtin.assert:
        that:
          - _k8s_info.resources | length == 0

    # TODO: ensure all ds/sts are fully rolled out
    # TODO: upgrades
