# SPDX-License-Identifier: Apache-2.0
# Copyright (c) VEXXHOST, Inc.

- name: Create ClusterIssuer
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: "{{ cluster_issuer_acme_azuredns_secret_name }}"
          namespace: cert-manager
          app.kubernetes.io/part-of: cert-manager
          app.kubernetes.io/managed-by: Ansible
        type: Opaque
        stringData:
          client-secret: "{{ cluster_issuer_acme_azuredns_client_secret }}"

      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: "{{ cluster_issuer_name }}"
          app.kubernetes.io/part-of: cert-manager
          app.kubernetes.io/managed-by: Ansible
        spec:
          acme:
            email: "{{ cluster_issuer_acme_email }}"
            server: "{{ cluster_issuer_acme_server }}"
            privateKeySecretRef:
              name: "{{ cluster_issuer_acme_private_key_secret_name }}"
            solvers:
              - dns01:
                  azureDNS:
                    clientID: "{{ cluster_issuer_acme_azuredns_client_id }}"
                    clientSecretSecretRef:
                      name: "{{ cluster_issuer_acme_azuredns_secret_name }}"
                      key: client-secret
                    subscriptionID: "{{ cluster_issuer_acme_azuredns_subscription_id }}"
                    tenantID: "{{ cluster_issuer_acme_azuredns_tenant_id }}"
                    resourceGroupName: "{{ cluster_issuer_acme_azuredns_resourcegroup_name }}"
                    hostedZoneName: "{{ cluster_issuer_acme_azuredns_hostedzone_name }}"
                    environment: "{{ cluster_issuer_acme_azuredns_environment }}"
