ceph_conf_overrides:
  - section: global
    option: osd crush chooseleaf type
    value: 0
  - section: mon
    option: auth allow insecure global id reclaim
    value: false

kubernetes_keepalived_interface: eth0

cilium_helm_values:
  operator:
    replicas: 1

csi_driver: local-path-provisioner

cluster_issuer_type: self-signed

ingress_nginx_helm_values:
  controller:
    config:
      worker-processes: 2

percona_xtradb_cluster_spec:
  allowUnsafeConfigurations: true
  pxc:
    size: 1
  haproxy:
    size: 1

keystone_helm_values:
  pod:
    replicas:
      api: 1

barbican_helm_values:
  pod:
    replicas:
      api: 1

glance_helm_values:
  conf:
    glance:
      DEFAULT:
        workers: 2
  pod:
    replicas:
      api: 1
glance_images:
  - name: cirros
    url: http://download.cirros-cloud.net/0.6.1/cirros-0.6.1-x86_64-disk.img
    min_disk: 1
    disk_format: raw
    container_format: bare
    is_public: true

cinder_helm_values:
  pod:
    replicas:
      api: 1
      scheduler: 1

placement_helm_values:
  pod:
    replicas:
      api: 1

coredns_helm_values:
  replicaCount: 1

nova_helm_values:
  conf:
    nova:
      DEFAULT:
        osapi_compute_workers: 2
        metadata_workers: 2
      conductor:
        workers: 2
      scheduler:
        workers: 2
  pod:
    replicas:
      api_metadata: 1
      osapi: 1
      conductor: 1
      scheduler: 1
      novncproxy: 1
      spiceproxy: 1

neutron_helm_values:
  conf:
    auto_bridge_add:
      br-ex: eth1
    neutron:
      DEFAULT:
        api_workers: 2
        rpc_workers: 2
        metadata_workers: 2
  pod:
    replicas:
      server: 1

heat_helm_values:
  conf:
    heat:
      DEFAULT:
        num_engine_workers: 2
      heat_api:
        workers: 2
      heat_api_cfn:
        workers: 2
      heat_api_cloudwatch:
        workers: 2
  pod:
    replicas:
      api: 1
      cfn: 1
      cloudwatch: 1
      engine: 1

octavia_amphora_image_disk_format: qcow2
octavia_helm_values:
  conf:
    octavia:
      controller_worker:
        volume_driver: volume_noop_driver
        workers: 2
  pod:
    replicas:
      api: 1
      worker: 1
      housekeeping: 1

magnum_image_disk_format: qcow2
magnum_images:
  - name: ubuntu-2004-v1.25.3
    url: https://object-storage.public.mtl1.vexxhost.net/swift/v1/a91f106f55e64246babde7402c21b87a/magnum-capi/ubuntu-2004-v1.25.3.qcow2
    distro: ubuntu-focal
magnum_helm_values:
  conf:
    magnum:
      conductor:
        workers: 2
  pod:
    replicas:
      api: 1
      conductor: 1
